import { resolveCompositionImportSource } from '../options'
import type { AstNode } from './ast'
import type { CompilerContext } from './context'
import { getMethodLike, type MethodLike } from './function-utils'
import { containsJsx, SKIP, walk } from './traverse'

/**
 * Prepares Vue 2 Composition API JSX transforms.
 *
 * The legacy @vue/babel-sugar-composition-api-render-instance plugin does not
 * turn setup() into an Options API method and does not rewrite arbitrary
 * source-level `this`. Its purpose is narrower: helpers generated by v-model
 * and v-on may contain `this.$*` / `this._*`, so those generated references
 * need a render instance captured while setup() is running.
 *
 * Source-level `this` remains invalid in Vue 2.7 setup() and is rejected here.
 * Compiler-generated helper access is requested later by v-model/v-on and is
 * injected by finalizeCompositionAPI().
 */
export function transformCompositionAPI(context: CompilerContext): void {
  const setupMethods = collectSetupMethods(context)

  for (const method of setupMethods) {
    context.registerSetupFunction(method.fn, method.body)
    assertNoSourceThisInSetup(method, context)
  }

  const importSource = resolveCompositionImportSource(
    context.options.compositionAPI
  )
  if (!importSource) return

  // Mirrors @vue/babel-sugar-composition-api-inject-h: setup render functions
  // use the named h export rather than this.$createElement.
  if (
    context.options.injectH &&
    containsJsx(context.ast as unknown as AstNode) &&
    !context.hasTopLevelBinding('h')
  ) {
    context.requestExactNamedImport(importSource, 'h', 'h')
  }
}

/**
 * Injects getCurrentInstance() only when generated v-model/v-on code requested
 * a Vue 2 render instance. Vue 2.7 returns { proxy }, so native mode captures
 * the public Vue instance through `.proxy` before using $set/_n/_q/_i/_k.
 */
export function finalizeCompositionAPI(context: CompilerContext): void {
  const importSource = resolveCompositionImportSource(
    context.options.compositionAPI
  )
  if (!importSource) return
  context.finalizeCompositionRenderInstances(importSource)
}

function collectSetupMethods(context: CompilerContext): MethodLike[] {
  const setupMethods: MethodLike[] = []

  walk(context.ast as unknown as AstNode, node => {
    if (context.isCovered(node)) return SKIP
    const method = getMethodLike(node)
    if (method?.keyName === 'setup') setupMethods.push(method)
  })

  return setupMethods
}

function assertNoSourceThisInSetup(
  method: MethodLike,
  context: CompilerContext
): void {
  walk(method.fn, node => {
    // Arrow functions inherit setup()'s lexical this and are checked. A nested
    // normal function owns its own dynamic this and is outside this rule.
    if (
      node !== method.fn &&
      (node.type === 'FunctionExpression' || node.type === 'FunctionDeclaration')
    ) {
      return SKIP
    }

    if (node.type !== 'ThisExpression') return

    context.error(
      '`this` is undefined inside Vue 2.7 setup(). ' +
        'Use setup(props, context), refs/reactive state, imported composables, ' +
        'or context.emit/context.attrs/context.listeners/context.slots instead. ' +
        'Only compiler-generated v-model/v-on helpers are allowed to access ' +
        'the captured render instance.',
      node
    )
  })
}
